// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8ZUhCnWVCrf3iIhyxB9tDmkacl0dO5JA',
    appId: '1:189721503336:web:78d6115660402c7173fddd',
    messagingSenderId: '189721503336',
    projectId: 'pushnotification-83173',
    authDomain: 'pushnotification-83173.firebaseapp.com',
    storageBucket: 'pushnotification-83173.firebasestorage.app',
    measurementId: 'G-L3J6MG0ETB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1lSEXk0XfSk3T-CYae0qG22NxPRDZo64',
    appId: '1:189721503336:android:31316e87ceae1e9373fddd',
    messagingSenderId: '189721503336',
    projectId: 'pushnotification-83173',
    storageBucket: 'pushnotification-83173.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8ZUhCnWVCrf3iIhyxB9tDmkacl0dO5JA',
    appId: '1:189721503336:web:820ce6f899ef1a5273fddd',
    messagingSenderId: '189721503336',
    projectId: 'pushnotification-83173',
    authDomain: 'pushnotification-83173.firebaseapp.com',
    storageBucket: 'pushnotification-83173.firebasestorage.app',
    measurementId: 'G-T3J8JRDBFQ',
  );
}
